---
title: "Performance af Cloud Run"
output: html_notebook
---


```{r}
for (p in c("ggplot2", "readr")) if (!require(p, character.only=TRUE, quietly=TRUE)) install.packages(p)

#log <- read_csv("/home/j/Projekter/NitrogenSensor/gitlab/nitrogensensor/daisy/DaisyTestkoersel_performancelog.csv")
log <- read_csv("DaisyTestkoersel_performancelog.csv")
log
```


Her ses hvordan lokal kørsel skalerer lineært med antallet af kørsler - imens Cloud Run er svagt stigende i tid.
Lokal kørsel er på Jacobs PC - en relativt stærk bærbar med 8 kerner.

X-aksen er antal kørsler, y-aksen er tid i sekunder.

```{r}
##log <- read_csv("Projekter/NitrogenSensor/gitlab/nitrogensensor/daisy/DaisyTestkoersel_performancelog.csv")
ggplot(data = log, aes(x=kørsler, y=tid, group=log$type, color=type)) + geom_line() + geom_point() + ggtitle("Daisysimulering for Taastrup marken")
```


```{r}
ggplot(data = log, aes(x=kørsler, y=tid, group=log$type, color=type)) + geom_point() + ggtitle("Daisy runs on the KU Taastrup field")  + xlab("Number of simulations") + ylab("Duration (secs)")
```

```{r}
ggplot(data = log, aes(x=kørsler, y=tid, group=log$type, color=type)) + geom_line() + geom_point() + ggtitle("Daisy runs on the KU Taastrup field")  + xlab("Number of simulations") + ylab("Duration (secs)")
```

